# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "seeding birds..."
Bird.create(com_name: 'Killdeer', sci_name: 'Charadrius vociferus', conservation_status: 'Least Concern', image: 'https://cdn.download.ams.birds.cornell.edu/api/v1/asset/301221881/900', description: 'Common, large plover. Slender shape with long wings and tail. Look for two black breast bands, unique among plovers in its range. Often nests near human development: parking lots, school roofs, road edges, and farms, usually on bare gravel. Adults perform broken-wing displays to distract predators from their nests and young. Gathers in larger numbers in migration and winter, often in fields with short grass or barren dirt. Occurs throughout North America; more local along the Pacific coast of northern South America. Can be very vocal; listen for loud namesake “kill-deer” call.')
Bird.create(com_name: 'Common Raven', sci_name: 'Corvus corax', conservation_status: 'Least Concern', image: 'https://cdn.download.ams.birds.cornell.edu/api/v1/asset/300152741/900', description: 'Large, glossy-black bird with a wedge-shaped tail. Larger than a crow with a longer, thicker bill. Distinctive shape in flight, with rather long, swept-back wings and long tail. Note smoother, steadier wingbeats compared with faster, choppier wingbeats of crows. Extensive range throughout the Northern Hemisphere. Found in a wide variety of habitats, including desert, coniferous forest, coastlines, sagebrush, tundra, and grasslands. Often solitary or in pairs, but can gather in small groups. Typical call is a loud, guttural croak, but makes an astonishing variety of other strange noises.')
Bird.create(com_name: 'Sandhill Crane', sci_name: 'Antigone canadensis', conservation_status: 'Least Concern', image: 'https://cdn.download.ams.birds.cornell.edu/api/v1/asset/303217321/900', description: 'Large, long-legged bird shaped much like a heron. Gray body, sometimes with intense rusty staining. Adults have red crown. Often in large flocks at migration and wintering concentration points. Favors marshes and agricultural fields where they eat primarily grains. In flight, neck is outstretched, unlike herons with tucked necks. Snappy wingbeats. Listen for far-carrying bugling call.')
Bird.create(com_name: 'Mourning Dove', sci_name: 'Zenaida macroura', conservation_status: 'Least Concern', image: 'https://cdn.download.ams.birds.cornell.edu/api/v1/asset/60386921/900', description: 'Svelte with a long, pointed tail. Plain brown overall with dark spots on wing. Juvenile is covered with pale scaly pattern, but is much larger and longer-tailed than ground doves. Widespread and common throughout much of North America, from southern Canada to Panama, including the Caribbean. Found in a variety of habitats from agricultural fields to lightly wooded areas. Loves suburbs, where it often sits on telephone wires and visits bird feeders. Avoids dense forest, but found on forest edges. Usually seen in pairs or small flocks, sometimes gathering in larger numbers, especially in winter. Listen for distinctive cooing song and whistling wings as it takes off.')
Bird.create(com_name: 'American Kestrel', sci_name: 'Falco sparverius', conservation_status: 'Least Concern', image: 'https://cdn.download.ams.birds.cornell.edu/api/v1/asset/302366931/900', description: 'Petite falcon roughly the same size as Mourning Dove, but with a larger head and wider tail. In flight, note long, narrow wings and square-tipped tail. Often seen perched on telephone wires, along roadsides, in open country with short vegetation and few trees. From a perch or hovering, they usually drop to the ground to snatch small mammals and insects. Nests in cavities. Widespread across the Americas.')

puts "done seeding!"